// app_ng/src/app/layout/layout.component.ts
import { Component, inject } from "@angular/core";
import { AuthStateService } from "../auth/state/auth.state.service";
import { UserStateService } from "../auth/state/user.state.service";
import { SidebarComponent } from "./sidebar.component";

@Component({
  selector: "app-layout",
  standalone: true,
  imports: [SidebarComponent],
  template: `
    <header class="bg-gray-900 text-white text-center py-4">
      <h1 class="text-3xl font-bold">Rick And Morty Universum</h1>
    </header>

    <div>
      <app-sidebar />
      <main>
        <ng-content />
      </main>
    </div>
  `,
  styles: [
    `
      :host {
        display: flex;
        flex-direction: column;
        height: 100%;
      }

      :host > div {
        display: flex;
        flex: 1;
        overflow: hidden;
      }

      main {
        flex-grow: 1;
        overflow-y: auto;
        height: 100%;
        @apply bg-gray-100;
      }
    `,
  ],
})
export class LayoutComponent {
  user = inject(UserStateService).value;
  authService = inject(AuthStateService);
}

// app_vue/src/components/layout/Layout.vue
<script setup lang="ts">
import AppSidebar from "./AppSidebar.vue";
</script>

<template>
  <div class="layout">
    <header class="bg-gray-900 text-white text-center py-4">
      <h1 class="text-3xl font-bold">Rick And Morty Universum</h1>
    </header>

    <div>
      <AppSidebar />
      <main>
        <slot />
      </main>
    </div>
  </div>
</template>

<style scoped>
.layout {
  display: flex;
  flex-direction: column;
  height: 100%;
}

.layout > div {
  display: flex;
  flex: 1;
  overflow: hidden;
}

main {
  flex-grow: 1;
  overflow-y: auto;
  height: 100%;
  @apply bg-gray-100;
}
</style>
